### ISSUE TITLE
[MAINT]: add workflow file for java server tests

### ISSUE THREAD

**Issue by mvoemel** [mvoemel/studyflow#61]
```yml
name: Run Server Tests

on:
  push:
    paths:
      - 'server/**' # Trigger the workflow only if changes are made in the server directory
  pull_request:
    paths:
      - 'server/**' # Also trigger the workflow for pull requests with changes in the server directory

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin distribution
          java-version: '17'      # Adjust this to match your Java version (e.g., 8, 11, 17)

      # Step 3: Navigate to server directory and run Gradle tests
      - name: Run Gradle tests
        working-directory: server
        run: |
          ./gradlew test

```
